### ISSUE TITLE
sysctl should be run in pre-start

### ISSUE THREAD

**Issue by giner** [cloudfoundry-community/sysctl-release#2]
To make sure all jobs benefit from sysctl settings (such as net.core.somaxconn) they have to be applied in pre-start, before all other jobs start.

**Comment by cunnie** [comment]
If you submit a PR, I'll work with you to get it merged.

**Comment by cunnie** [comment]
Closing: it has been two years, and no PR to fix this has been submitted.

**Comment by giner** [comment]
@cunnie we have switched to [os-conf-release](https://github.com/cloudfoundry/os-conf-release/tree/master/jobs/sysctl) a while back
